### ISSUE TITLE
Libgraphql

### ISSUE THREAD

**Issue by andreyz** [stepanhruda/GraphQL-Swift#1]
Thanks for this initiative! I'm fairly new to GraphQL and wonder why you decided to re-implement parser yourself instead of binding to libgraphql pure C API?

**Comment by stepanhruda** [comment]
Do you mean https://github.com/graphql/libgraphqlparser? Several reasons, actually:
1. _libgraphqlparser_ is only a query parser. This repo is meant to be a full spec implementation to be used as a Swift package on the server side, not the client side, similar to https://github.com/graphql/graphql-js
2. When I started on this repo, _libgraphqlparser_ didn't exist yet. All of the functionality that it could save is already implemented anyway.

**Comment by andreyz** [comment]
Thanks for replying, Stepan! Both 1 & 2 make sense.

**Comment by andreyz** [comment]
I'd recommend adding something like the explanation you've given me to README

> This repo is meant to be a full spec implementation to be used as a Swift package on the server side, not the client side, similar to https://github.com/graphql/graphql-js

It'd probably pre-empt questions like mine in the future.
